spring:
  main:
    banner-mode: off

logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO
    com.example.TaskAPI: INFO
    com.example.TaskAPI.error.client: DEBUG
    org.hibernate.SQL: WARN
  file:
    path: ${TASKAPI_LOG_DIR:/app/logs}

management:
  tracing:
    sampling:
      probability: 0.1