logging:
  level:
    com.example.TaskAPI: DEBUG
    sql: DEBUG
  file:
    path: ${TASKAPI_LOG_DIR:logs}

management:
  tracing:
    export:
      enabled: false
  otlp:
    metrics:
      export:
        enabled: false