logging:
  level:
    com.example.TaskAPI: DEBUG
    sql: DEBUG
  file:
    name: logs/identityapi.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 14
      total-size-cap: 500MB
      file-name-pattern: logs/identityapi-%d{yyyy-MM-dd}.%i.log.gz
  structured:
    format:
      file: ecs

management:
  tracing:
    export:
      enabled: false
  otlp:
    metrics:
      export:
        enabled: false